### ISSUE TITLE
Pouch contents wiped on relogging to server

### ISSUE THREAD

**Issue by DrUltraLux** [Cynosphere-mc/Scout#22]
Anything placed in the pouch when I logout is wiped when I try to log back in again. 
Replicates every single time. Nothing in the logs. 

Like it just never saves.

Running Minecraft 1.19.2 Fabric 0.62
Server is running Fabric MC 0.14.9

![image](https://user-images.githubusercontent.com/63906224/193384112-505216d4-d93f-4d82-8816-a673529d0787.png)

**Comment by deli73** [comment]
having similar issues, unsure how to replicate. seems to be wiped on server restart for us. 

the server's mod list is as follows:
```
advancementfix-0.1.0.jar
affectionate-1.1.2+1.19.jar
appleskin-fabric-mc1.19-2.4.1.jar
architects-palette-fabric-2.1.1.jar
architectury-6.3.49-fabric.jar
aurorasdecorations-1.0.0-beta.10+1.19.jar
boat-with-everything-1.1.0.jar
Bookshelf-Fabric-1.19.2-16.1.11.jar
bouncycastle-1.0.2+1.19.jar
chewstuff-mc1.19.2-1.0.0.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.8.jar
CosmeticArmor-1.19-1.4.0.jar
create-fabric-1.19.2-0.5.0f-776.jar
drogtor-1.1.3.jar
effective-1.6+1.19.2.jar
emi-0.4.2+1.19.jar
enchancement-1.19-7.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.8.jar
excorrelation-1.0.25.jar
fabrication-3.1.3+1.19.jar
fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar
fabrictailor-2.0.1.jar
farmers-delight-fabric-1.19.2-1.3.7.jar
fastfurnace-1.19.2-5.jar
ferritecore-5.0.0-fabric.jar
geckolib-quilt-1.19-3.1.37.jar
healingcampfire-fabric_1.19.2-4.0.jar
illuminations-1.10.11.jar
Interlink-1.19.2-2.0.0.jar
limits_grapple-0.6.3-1.19.jar
lithium-fabric-mc1.19.2-0.10.2.jar
matchbox-0.2.4-1.19.jar
mermod-fabric-2.21.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar
Origins-1.19.2-1.7.1.jar
packages-fabric-1.19.2-3.jar
Pehkui-3.6.0+1.14.4-1.19.3.jar
pettable-1.3.1.jar
polaroid-1.0.1-zml-SNAPSHOT.jar
qfapi-4.0.0-beta.20_qsl-3.0.0-beta.21_fapi-0.66.0_mc-1.19.2.jar
scout-1.19-1.1.1.jar
soundphysics-fabric-1.19.2-1.0.16.jar
starlight-1.1.1+fabric.ae22326.jar
switchy-1.5.0+1.19.jar
TerraBlender-fabric-1.19.2-2.0.1.130.jar
tooltipfix-1.1.1-1.19.jar
TransparentCosmetics-1.5.0.jar
trinkets-3.4.0.jar
unobtrusive_vines-1.0.0.jar
unobtrusive-bats-3.0.1+1.19.2.jar
voicechat-quilt-1.19.2-2.3.15.jar
walljump-unofficial-1.6.1b-all+1.19.2.jar
yttr-6.614+1.19.jar
```

**Comment by Cynosphere** [comment]
@deli73 Your issue isn't related to the original issue. That just sounds like the restart wasn't graceful and player data didn't get saved.

**Comment by deli73** [comment]
oh, sorry. any idea what'd cause that?

**Comment by SebSemos** [comment]
Yep. similar issue on my server too. For me it sometimes vanishes when I put items them in the pouches. It seems to happen after a switch from creative mode. You put the item, it dissapear, sometime you get it back by clicking on it or trying to put another item in the same slot. After it happen once this error come in the log each time you pick or place something anywhere in the inventory : 

> Error executing task on Client
> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1263.method_5447(int, net.minecraft.class_1799)" because "this.field_7871" is null
> 	at net.minecraft.class_1735.method_44206(class_1735.java:66)
> 	at net.minecraft.class_1703.method_7610(class_1703.java:592)
> 	at net.minecraft.class_634.method_11153(class_634.java:1110)
> 	at net.minecraft.class_2649.method_11439(class_2649.java:44)
> 	at net.minecraft.class_2649.method_11054(class_2649.java:11)
> 	at net.minecraft.class_2600.method_11072(class_2600.java:22)
> 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
> 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
> 	at net.minecraft.class_1255.method_5383(class_1255.java:116)
> 	at net.minecraft.class_310.method_1523(class_310.java:1129)
> 	at net.minecraft.class_310.method_1514(class_310.java:768)
> 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 

Reloging in the server get rid of the error. 
(I have the 1.1.1 of your mod, to get it working with IPN 1.7.0)

**Comment by Bluberry-Kat** [comment]
also just experienced this (on integrated server). seems to be inconsistent.  
i *haven't* experienced this on 1.18. could it be a regression?
