### ISSUE TITLE
 java.lang.ClassCastException error

### ISSUE THREAD

**Issue by UsernameNotActive** [Cynosphere-mc/Scout#25]
Sometimes my world would crash and I would get this error. I am using the 1.19 v1.1.1 of the mod on fabric 1.19.2.

This is the crash log:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022-10-12 09:39:17
Description: Rendering screen

java.lang.ClassCastException: class net.minecraft.class_1739 cannot be cast to class pm.c7.scout.item.BaseBagItem (net.minecraft.class_1739 and pm.c7.scout.item.BaseBagItem are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)
	at pm.c7.scout.compat.ScoutREIClientPlugin.lambda$registerScreens$0(ScoutREIClientPlugin.java:28)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:142)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.isInZone(ExclusionZonesImpl.java:75)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.canItemSlotWidgetFit(EntryListWidget.java:94)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.notSteppingOnExclusionZones(EntryListWidget.java:85)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionListener.notSteppingOnExclusionZones(RegionListener.java:73)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.updateEntriesPosition(EntryStacksRegionWidget.java:334)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.method_25394(EntryStacksRegionWidget.java:108)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.method_25394(FavoritesListWidget.java:214)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:330)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:239)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:398)
	at net.minecraft.class_757.handler$zhh000$renderScreenPost(class_757.java:9567)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pm.c7.scout.compat.ScoutREIClientPlugin.lambda$registerScreens$0(ScoutREIClientPlugin.java:28)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:142)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.isInZone(ExclusionZonesImpl.java:75)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.canItemSlotWidgetFit(EntryListWidget.java:94)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.notSteppingOnExclusionZones(EntryListWidget.java:85)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionListener.notSteppingOnExclusionZones(RegionListener.java:73)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.updateEntriesPosition(EntryStacksRegionWidget.java:334)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.method_25394(EntryStacksRegionWidget.java:108)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.method_25394(FavoritesListWidget.java:214)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:330)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:239)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:398)
	at net.minecraft.class_757.handler$zhh000$renderScreenPost(class_757.java:9567)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (386, 158). Absolute: (1547.000000, 634.000000)
	Screen size: Scaled: (480, 247). Absolute: (1920, 986). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Unkillablegaming'/219, l='ClientLevel', x=2.62, y=63.00, z=18.30]]
	Chunk stats: 1024, 318
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,77,0), Section: (at 0,13,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13719 game time, 13719 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, VanillaTweaks_r571967.zip, EmbellishedStone-1.19-1.0.0.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1741636040 bytes (1660 MiB) / 7314866176 bytes (6976 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=25.20.100.6576
	Graphics card #1 name: NVIDIA GeForce 940MX
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x134d
	Graphics card #1 versionInfo: DriverVersion=24.21.13.9836
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18682.39
	Virtual memory used (MB): 14374.27
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 623.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.2
		additionalstructures: Additional Structures 4.1.0
		adorn: Adorn 3.6.1+1.19
		advancednetherite: Advanced Netherite 1.6.4-1.19.2
		architectury: Architectury 6.2.46
		armorstatues: Armor Statues 4.0.0
		badpackets: Bad Packets 0.2.0
		bclib: BCLib 2.1.1
		betteradvancements: Better Advancements 0.2.2.142
		betterbeds: Better Beds 1.2.0
		bettercombat: Better Combat 1.4.4+1.19
		betterend: Better End 2.1.1
		betterf3: BetterF3 1.4.0
		betternether: Better Nether 7.1.1
		bettervillage: Better village 2.0.0
		bewitchment: Bewitchment 1.19-5
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.7.0
			midnightlib: MidnightLib 0.5.2
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.1
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		blockus: Blockus 2.5.2+1.19.2
		blossom: Blossom 1.0.5
		bowinfinityfix: Bow Infinity Fix 2.5.0
		byg: Oh The Biomes You'll Go 2.0.0.12
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		charm: Charm 4.2.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.50
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.0+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			spectrelib: SpectreLib 0.8.1+1.19
		connectivity: Connectivity Mod 1.19-3.3
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+1
		cosmetic-armor: Cosmetic Armor 1.4.0
		cozy: Cozy 1.0.2
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		creeperoverhaul: Creeper Overhaul 2.0.3
		ctov: ChoiceTheorem's Overhauled Villages 3.1
		cull-less-leaves: Cull Less Leaves 1.0.2
		cullleaves: Cull Leaves 2.3.4
		dataattributes: Data Attributes 1.2.7
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.7.1
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		dragonloot: DragonLoot 1.1.2
		dungeons_arise: When Dungeons Arise 2.1.51
		dynamicfps: Dynamic FPS 2.2.0
		edenring: EdenRing 0.6.4
		effectivecrystals: Effective Crystals 1.0+1.19.2
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchantinginfuser: Enchanting Infuser 4.2.1
		endrem: End Remastered 5.1.2
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.3
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		extended_armor_bars: Extended Armor Bars 1.2.1
		extra: Extra classes 1.0.0
		extra_classes_origins: Extra Classes - Origins 1.0.0
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		fastload: Fast Load 1.1.4+1.19
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		fpsreducer: FPS Reducer 1.19.2-2.1
		fwaystones: Fabric Waystones 3.0.3+mc1.19.2
			pinlib: PinLib 0.1.3+1.19
		geckolib3: Geckolib 3.1.22
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		geodes: More Geodes 1.5
		glowingbanners: Glow Banners 1.2.0
		graveyard: The Graveyard 1.10
		graveyard_biomes: The Graveyard Biomes 1.2
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		healingcampfire-fabric: Healing Campfire (Fabric) 3.5
		healthoverlay: Health Overlay 7.1.1
		hollowwoods: HollowWoods 1.2.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		ia: Immersive Amethyst 1.0.5
		iceberg: Iceberg 1.0.46
		immersive_paintings: Immersive Paintings 0.2.0+1.19.2
		imst: Immersive structures 2.0.2
		incendium: Incendium 5.1.2
		indium: Indium 1.0.9+mc1.19.2
		infusion_table: Infusion Table 1.1.0
		infwithmend: Infinity with Mending 1.0.0
		itemborders: Item Borders 1.1.6
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.5.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		levelz: LevelZ 1.4.0
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		libraryferret: Library ferret 3.0.0
		lithium: Lithium 0.8.3
		lootr: Lootr 0.3.20.58
		mcda: MC Dungeons Armors 2.1.0
		mcdw: MC Dungeons Weapons 4.4.0-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcwpaintings: Macaw's Paintings 1.0.3
		medievalentity: Medievial Entity 2.5.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		modid: ibarn's origins addon 1.0.5-fabric-1.18
		modmenu: Mod Menu 4.0.6
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers: More Villagers 4.0.2
		mythicupgrades: Mythic Upgrades 1.2.1
		origins: Origins 1.7.0
			apoli: Apoli 2.6.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
		origins-classes: Origins: Classes 1.4.0
		origins-plus-plus: Origins++ 1.7.2
		originsumbrellas: Origins: Umbrellas 1.5.4
		passiveshield-fabric: Passive Shield (Fabric) 2.1
		patchouli: Patchouli 1.19.2-76-FABRIC
		pehkui: Pehkui 3.5.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		player-animator: Player Animator 0.4.0-test1
		playtics_deco: PlayTics Deco 1.0
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.45.0+1.19.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
		puzzleslib: Puzzles Lib 4.3.9
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		qolfixes: QoLFixes 2.0.1-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		repurposed_structures: Repurposed Structures 6.0.5+1.19
		resourcefullib: Resourceful Lib 1.1.1
		roughlyenoughitems: Roughly Enough Items 9.1.530
			error_notifier: Error Notifier 1.0.9
		scout: Scout 1.1.1
		simple_backpack: SimpleBackpack 1.3.21
		simply_houses: Simply Houses 1.1.2-1.19
		simplyswords: Simply Swords 1.5-1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.9+mc1.19.2-build.60
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		soulsweapons: Marium's Soulslike Weaponry 0.9.5
		starterkit-fabric: Starter Kit (Fabric) 3.7
		statues: Statues 1.1.1
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		terrablender: TerraBlender 2.0.1.127
		terrestria: Terrestria 5.0.2
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.1.1
			terraform-config-api-v1: Terraform Config API (v1) 4.1.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 4.1.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.1.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.1.1
			terraform-tree-api-v1: Terraform Tree API (v1) 4.1.1
			terrestria-client: Terrestria: Client 5.0.2
			terrestria-common: Terrestria: Common 5.0.2
			terrestria-worldgen: Terrestria: World Generation 5.0.2
		toolleveling: ToolLeveling+ 1.19.2-1.4.1
		tooltipfix: ToolTip Fix 1.0.5-1.19
		trade_cycling: Trade Cycling 1.19.2-1.0.5
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.0
		treeharvester-fabric: Tree Harvester (Fabric) 5.2
		trinkets: Trinkets 3.4.0
		universal_ores: Universal Ores 1.4.2
		uselessreptile: Useless Reptile 0.1.3
		utilitybelt: Utility Belt 1.1.1
		wilderwild: Wilder Wild 1.1.1-Fabric+1.19.2
			frozenblocklib: FrozenBlock's Library 1.1.1-Fabric+1.19.2
			nbtcrafting: NBT Crafting 2.2.0+mc1.19
		windchimes: Windchimes 1.2.1
		wthit: wthit 5.11.3
		xaerominimap: Xaero's Minimap 22.13.2
		xaeroworldmap: Xaero's World Map 1.26.6
		yigd: You're in Grave Danger 1.4.4
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce 940MX/PCIe/SSE2 GL version 3.2.0 NVIDIA 398.36, NVIDIA Corporation
	Window size: 1920x986
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/VanillaTweaks_r571967.zip, file/EmbellishedStone-1.19-1.0.0.zip, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Unkillablegaming'/219, l='ServerLevel[Fabric]', x=2.62, y=63.00, z=18.30]]
	Data Packs: vanilla, Fabric Mods, file/BlazeandCaves Advancements Pack 1.15.zip, file/VanillaTweaks_c974842.zip, file/cauldron concrete v2.0.6.zip, file/clgd-larger-ore-veins-deluxe-1.1.zip, file/custom nether portals v2.3.6.zip, file/double shulker shells v1.3.3.zip, file/dragon drops v1.3.3.zip, file/fast leaf decay v2.0.6.zip, file/more mob heads v2.10.1.zip
	World Generation: Stable

**Comment by Cynosphere** [comment]
shedaniel stop rewriting REI's API challenge (impossible)
