### ISSUE TITLE
Unable to shift-click items to pouches.

### ISSUE THREAD

**Issue by Xerillic** [Cynosphere-mc/Scout#26]
[16:55:44] [Server thread/INFO]: Saving and pausing game... [16:55:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld [16:55:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether [16:55:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end [16:55:52] [Render thread/ERROR]: Error executing task on Client java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1263.method_5447(int, net.minecraft.class_1799)" because "this.field_7871" is null 	at net.minecraft.class_1735.method_44206(class_1735.java:66) ~[client-intermediary.jar:?] 	at net.minecraft.class_1703.method_7610(class_1703.java:592) ~[client-intermediary.jar:?] 	at net.minecraft.class_634.method_11153(class_634.java:1110) ~[client-intermediary.jar:?] 	at net.minecraft.class_2649.method_11439(class_2649.java:44) ~[client-intermediary.jar:?] 	at net.minecraft.class_2649.method_11054(class_2649.java:11) ~[client-intermediary.jar:?] 	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?] 	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?] 	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?] 	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?] 	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?] 	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?] 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?] [16:55:54] [Server thread/INFO]: Saving and pausing game...

**Comment by Cynosphere** [comment]
You shouldn't even be able to, as they're only "inventory slots" just to be recognized by the screen. Annoying that it crashes.

**Comment by Xerillic** [comment]
It doesnt crash, it just throws an error. Is it possible to enable this functionality? I assume doing so will also allow items that are picked up to stack into the pouches instead of going just to your inventory
