### ISSUE TITLE
Scout Not Running on Minecraft Server

### ISSUE THREAD

**Issue by DaSharpe** [Cynosphere-mc/Scout#3]
# Issue
When attempting to run a Minecraft server with scout installed, the Minecraft server will fail to start.

# Version
Minecraft: 1.20.1
Fabric Loader: 0.15.6 or 0.15.7
Scout: 2.0.1 or 2.0.0
Trinkets: 3.7.2
Fabric API: 0.91.0+
OS: Ubuntu 22.04.1 LTS

# Log
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 16 1000 0 4096 Mar 18 03:28 /data'
[mc-image-helper] 03:59:27.182 INFO  : Fabric launcher for minecraft 1.20.1 loader 0.15.6 is already available
[mc-image-helper] 03:59:29.837 INFO  : Created/updated 1 property in /data/server.properties
[init] Setting initial memory to 24G and max to 24G
[init] Starting the Minecraft server...
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[03:59:34] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.6
[03:59:34] [main/WARN]: Warnings were found!
 - Mod 'Scout' (scout) 2.0.1+1.20.1 recommends version 1.1.3 or later of emi, which is missing!
	 - You should install version 1.1.3 or later of emi for the optimal experience.
[03:59:34] [main/INFO]: Loading 50 mods:
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.1
	- scout 2.0.1+1.20.1
	   |-- lib39-core 1.5.0-experimental6.1+1.20.1
	   \-- lib39-dessicant 1.5.0-experimental6.1+1.20.1
	- trinkets 3.7.2
	   |-- cardinal-components-base 5.2.0
	   \-- cardinal-components-entity 5.2.0
[03:59:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[03:59:34] [main/INFO]: Compatibility level set to JAVA_16
[03:59:34] [main/INFO]: Compatibility level set to JAVA_17
[03:59:35] [main/WARN]: Error loading class: net/minecraft/unmapped/C_mxrobsgg$C_wdomexrk (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_mxrobsgg$C_wdomexrk)
[03:59:35] [main/WARN]: Error loading class: net/minecraft/server/network/ServerPlayerEntity$2 (java.lang.ClassNotFoundException: net/minecraft/server/network/ServerPlayerEntity$2)
[03:59:35] [main/WARN]: Error loading class: net/minecraft/unmapped/C_mxrobsgg$C_wdomexrk (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_mxrobsgg$C_wdomexrk)
[03:59:35] [main/WARN]: Error loading class: net/minecraft/server/network/ServerPlayerEntity$2 (java.lang.ClassNotFoundException: net/minecraft/server/network/ServerPlayerEntity$2)
[03:59:35] [main/WARN]: Error loading class: net/minecraft/unmapped/C_mxrobsgg$C_wdomexrk (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_mxrobsgg$C_wdomexrk)
[03:59:35] [main/WARN]: Error loading class: net/minecraft/server/network/ServerPlayerEntity$2 (java.lang.ClassNotFoundException: net/minecraft/server/network/ServerPlayerEntity$2)
[03:59:35] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[03:59:40] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'scout'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.6-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5225
	at pm.c7.scout.config.ScoutConfig.getSavedConfig(ScoutConfig.java:105) ~[Scout-2.0.1+1.20.1.jar:?]
	at pm.c7.scout.config.ScoutConfig.<clinit>(ScoutConfig.java:205) ~[Scout-2.0.1+1.20.1.jar:?]
	at pm.c7.scout.Scout.onInitialize(Scout.java:37) ~[Scout-2.0.1+1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5225
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at pm.c7.scout.config.ScoutConfig.getSavedConfig(ScoutConfig.java:105) ~[Scout-2.0.1+1.20.1.jar:?]
	at pm.c7.scout.config.ScoutConfig.<clinit>(ScoutConfig.java:205) ~[Scout-2.0.1+1.20.1.jar:?]
	at pm.c7.scout.Scout.onInitialize(Scout.java:37) ~[Scout-2.0.1+1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 7 more
2024-03-18T03:59:40.829Z	INFO	mc-server-runner	Done

**Comment by Cynosphere** [comment]
Fixed in 2.0.2

**Comment by DaSharpe** [comment]
Dang you're quick!

2.0.2 Fixed the original issue of minecraft/class_5225 But it seems that it is now complaining about minecraft/class_310 and failing to load datapacks. There are currently no datapacks being loaded in. Only Fabric API, Trinkets, and Scout.

Here is the new log with the same items cut out.

[04:43:17] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[04:43:22] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:43:24] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/class_310
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
	at pm.c7.scout.ScoutUtil.getPlayerScreenHandler(ScoutUtil.java:135) ~[Scout-2.0.2+1.20.1.jar:?]
	at net.minecraft.class_2371.handler$zia000$scout$fixIndexingSlots(class_2371.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_2371.get(class_2371.java) ~[server-intermediary.jar:?]
	at java.util.AbstractList$Itr.next(Unknown Source) ~[?:?]
	at net.minecraft.class_1867.handler$zfe000$fabric-recipe-api-v1$cacheRequiresTesting(class_1867.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867.<init>(class_1867.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:100) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at pm.c7.scout.ScoutUtil.getPlayerScreenHandler(ScoutUtil.java:135) ~[Scout-2.0.2+1.20.1.jar:?]
	at net.minecraft.class_2371.handler$zia000$scout$fixIndexingSlots(class_2371.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_2371.get(class_2371.java) ~[server-intermediary.jar:?]
	at java.util.AbstractList$Itr.next(Unknown Source) ~[?:?]
	at net.minecraft.class_1867.handler$zfe000$fabric-recipe-api-v1$cacheRequiresTesting(class_1867.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867.<init>(class_1867.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:100) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 5 more
2024-03-18T04:43:24.257Z	INFO	mc-server-runner	Done

**Comment by Senjosei** [comment]
+1 yep can confirm, im guessing its because of this [https://github.com/Cynosphere-mc/Scout/blob/e323de2d574f38c7e53e61ba1450404fd0ddfb0d/src/main/java/pm/c7/scout/ScoutUtil.java#L135](https://github.com/Cynosphere-mc/Scout/blob/e323de2d574f38c7e53e61ba1450404fd0ddfb0d/src/main/java/pm/c7/scout/ScoutUtil.java#L135)
```
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_310
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
        at pm.c7.scout.ScoutUtil.getPlayerScreenHandler(ScoutUtil.java:135) ~[Scout-2.0.2+1.20.1.jar:?]
        at net.minecraft.class_2371.handler$gmb000$scout$fixIndexingSlots(class_2371.java:1015) ~[server-intermediary.jar:?]
        at net.minecraft.class_2371.get(class_2371.java) ~[server-intermediary.jar:?]
        at java.util.AbstractList$Itr.next(AbstractList.java:371) ~[?:?]
        at java.util.AbstractCollection.removeAll(AbstractCollection.java:368) ~[?:?]
        at com.beansgalaxy.backpacks.Constants.readItemList(Constants.java:105) ~[BeansBackpacks-fabric-1.20.1-0.18-v2.jar:?]
        at net.minecraft.class_5350.handler$bbc000$beansbackpacks$catchDataPacks(class_5350.java:2038) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        ... 3 more
```
